@startuml class diagram

hide empty methods
hide empty attributes

class DocumentManager{}

class Document{}

class ArrayList{}

DocumentManager -- ArrayList : uses
ArrayList -- Document : stores
DocumentManager .. Document : manage 

@enduml